services:
  node-red:
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    volumes:
      - ./node-red/data:/data
      - ./certs:/certs
    environment:
      - TZ=Europe/Madrid
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      - iot_agent_net
      - keyrock_net
      - orion_net
      - mucc-sco-p1-net
  certificate:
    image: cert-gen
    volumes:
      - ./certs:/certs
    environment:
      - DOMAIN=10.0.2.15
      - SUBJ_C=ES
      - SUBJ_ST=Valencia
      - SUBJ_L=Valencia
      - SUBJ_O="Seguridad de las Cosas"
      - SUBJ_OU=SCO
    networks:
      - mucc-sco-p1-net
  keyrock-db:
    image: mysql:5.7
    restart: always
    networks:
      - keyrock_net
    expose:
      - "3306"
    volumes:
      - ./keyrock-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  keyrock:
    depends_on:
      - keyrock-db
    image: fiware/idm:8.4.0
    networks:
      keyrock_net:
        ipv4_address: 192.168.40.10
    ports:
      - 3005:3005
      - 3443:3443
    volumes:
      - ./certs:/opt/fiware-idm/certs
    environment:
      - DEBUG=idm:*
      - IDM_HOST=http://192.168.40.10:3005
      - IDM_PORT=3005
      - IDM_HTTPS_PORT=3443
      - IDM_HTTPS_ENABLED=true
      - IDM_DB_HOST=keyrock-db
      - IDM_DB_USER=root
      - IDM_DB_PASS=secret
      - IDM_ADMIN_USER=admin
      - IDM_ADMIN_EMAIL=admin@test.com
      - IDM_ADMIN_PASS=1234567890
  orion-db:
    image: mongo:4.4
    restart: unless-stopped
    expose:
      - "27017"
    networks:
      - orion_net
    volumes:
      - ./orion-db/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  hivemq:
    image: hivemq/hivemq-ce:2024.7
    ports:
      - 8883:8883
    networks:
      - iot_agent_net
    volumes:
      - ./hivemq/conf:/opt/hivemq/conf
      - ./certs:/certs
  orion:
    image: fiware/orion:latest
    restart: unless-stopped
    ports:
      - 1028:1028
    networks:
      orion_net:
        ipv4_address: 192.168.41.10
    volumes:
      - ./certs:/opt/orion/certs/
    environment:
      - ORION_MONGO_URI=mongodb://root:root@orion-db:27017
      - ORION_INSECURE_NOTIF=true
      - ORION_HTTPS=true
      - ORION_HTTPS_CERTFILE=/opt/orion/certs/cert.crt
      - ORION_HTTPS_KEYFILE=/opt/orion/certs/key.key
      - ORION_HOST=https://192.168.41.10
      - ORION_PORT=1028
      - NODE_TLS_REJECT_UNAUTHORIZED=0
  # CONFIGURACIÓN CON NGINX    
  # nginx:
  #   depends_on:
  #     - wilma
  #   image: nginx:latest
  #   restart: unless-stopped
  #   ports:
  #     - 1026:1026
  #   volumes:
  #     - ./nginx/conf/:/etc/nginx/conf.d/:ro
  #     - ./nginx/www/default/:/var/www/default/:ro
  # wilma:
  #   depends_on:
  #     - keyrock
  #   image: fiware/pep-proxy
  #   ports:
  #     - "1027:1027"
  #   # volumes:
  #   #   - ./certs:/opt/fiware-pep-proxy/certs
  #   #   - ./wilma-config/config.js:/opt/fiware-pep-proxy/config.js
  #   environment:
  #     - PEP_PROXY_PDP=idm
  #     - PEP_PROXY_AUTH_FOR_NGINX=true
  #     - PEP_PROXY_PORT=1027
  #     - PEP_PROXY_HTTPS_ENABLED=false
  #     - PEP_PROXY_AUTH_ENABLED=false
  #     - PEP_PROXY_APP_ID=d6ef7f8c-7c70-4b59-8e3d-121bcd316d47
  #     - PEP_PROXY_USERNAME=pep_proxy_f196e6c7-4584-4918-88d3-d5ea0aeac36c
  #     - PEP_PASSWORD=pep_proxy_114a7dfc-f694-4800-bd42-a350600e629c
  #     - PEP_PROXY_IDM_HOST=10.0.2.15
  #     - PEP_PROXY_IDM_PORT=3005 # https 3443
  #     # Keyrock
  #     - PEP_PROXY_IDM_HOST=10.0.2.15
  #     - PEP_PROXY_IDM_PORT=3005
  #     - PEP_PROXY_IDM_SSL_ENABLED=false
  #     - NODE_TLS_REJECT_UNAUTHORIZED=0
  wilma:
    depends_on:
      - keyrock
      - iot-agent-json
    restart: always
    image: fiware/pep-proxy
    ports:
      - "1026:1026"
    networks:
      iot_agent_net:
        ipv4_address: 192.168.42.20
      keyrock_net:
        ipv4_address: 192.168.40.20
      orion_net:
        ipv4_address: 192.168.41.20
    volumes:
      - ./certs:/opt/fiware-pep-proxy/certs
      - ./wilma-config/config.js:/opt/fiware-pep-proxy/config.js
    environment:
      - PEP_PROXY_PDP=idm
      - PEP_PROXY_PORT=1026
      - PEP_PROXY_HTTPS_PORT=1026
      - PEP_PROXY_HTTPS_ENABLED=true
      - PEP_PROXY_AUTH_ENABLED=false
      - PEP_PROXY_APP_ID=d6ef7f8c-7c70-4b59-8e3d-121bcd316d47
      - PEP_PROXY_USERNAME=pep_proxy_f196e6c7-4584-4918-88d3-d5ea0aeac36c
      - PEP_PASSWORD=pep_proxy_114a7dfc-f694-4800-bd42-a350600e629c
      # Keyrock
      - PEP_PROXY_IDM_HOST=192.168.40.10
      - PEP_PROXY_IDM_PORT=3443
      - PEP_PROXY_IDM_SSL_ENABLED=true
      # Orion
      - PEP_PROXY_APP_HOST=192.168.41.10
      - PEP_PROXY_APP_PORT=1028
      - PEP_PROXY_APP_SSL_ENABLED=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0
  iot-agent-json-db:
    image: mongo:4.4
    restart: unless-stopped
    expose:
      - "27017"
    networks:
      - iot_agent_net
    volumes:
      - ./iot-agent-json-db/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  iot-agent-json:
    image: fiware/iotagent-json:3.3.0
    restart: unless-stopped
    networks:
      iot_agent_net:
        ipv4_address: 192.168.42.10
    ports:
      - 4061:4061 # North port: Management
      - 7896:7896 # South port: Data
    volumes:
      - ./certs:/opt/iotagent-json/certs
    environment:
      # IoT Agent Node Lib variables
      - IOTA_NORTH_PORT=4061
      - IOTA_PROVIDER_URL=https://192.168.42.10:4061
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_MONGO_HOST=iot-agent-json-db
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_USER=root
      - IOTA_MONGO_PASSWORD=root
      - IOTA_MONGO_AUTH_SOURCE=admin
      - IOTA_CB_HOST=192.168.42.20
      - IOTA_CB_URL=https://192.168.42.20:1026
      - IOTA_CB_PORT=1026
      - IOTA_CB_HTTPS=true
      - IOTA_HTTP_PORT=7896
      - IOTA_HTTP_KEY=/opt/iotagent-json/certs/key.key
      - IOTA_HTTP_CERT=/opt/iotagent-json/certs/cert.crt
      - IOTA_HTTP_REHECT_UNAUTHORIZED=false
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - IOTA_AUTH_ENABLED=true
      - IOTA_AUTH_PERMANENT_TOKEN=true
      - IOTA_AUTH_TYPE=oauth2
      - IOTA_AUTH_HOST=192.168.42.20
      - IOTA_AUTH_PORT=3443
      - IOTA_AUTH_URL=https://192.168.42.20:3443 # Parece que funciona pero Quizá sea directamente Keyrock (192.168.40.10) No estoy seguro porque el IoT Agent debería atacar a Keyrock directamente ¿?
      - IOTA_AUTH_TOKEN_PATH=/oauth2/token
      - IOTA_AUTH_HEADER=Authorization
      - IOTA_AUTH_CLIENT_ID=d6ef7f8c-7c70-4b59-8e3d-121bcd316d47
      - IOTA_AUTH_CLIENT_SECRET=79f7a7b3-fe5c-47c5-a3e5-c69592e2a47a
      - IOTA_AUTH_SSL=true
networks:
  mucc-sco-p1-net: null
  keyrock_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.40.0/24
          gateway: 192.168.40.1
  orion_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.41.0/24
          gateway: 192.168.41.1
  iot_agent_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.42.0/24
          gateway: 192.168.42.1